version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: pokemon-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pokemon_catalog
    ports:
      - "5432:5432"